<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->require_min_level(1);
        if( !$this->is_role('admin') ){
            redirect('restringido');
        }
        $this->load->model('Detalle_model');
    } 

    /*
     * Listing of detalles
     */
    function index()
    {
        $data['detalles'] = $this->Detalle_model->get_all_detalles();
        
        $data['_view'] = 'detalle/index';
        $this->load->view('layouts/admin',$data);
    }

    /*
     * Adding a new detalle
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_venta' => $this->input->post('id_venta'),
				'producto' => $this->input->post('producto'),
				'cantidad' => $this->input->post('cantidad'),
				'precio' => $this->input->post('precio'),
				'importe' => $this->input->post('importe'),
				'costo' => $this->input->post('costo'),
            );
            
            $detalle_id = $this->Detalle_model->add_detalle($params);
            redirect('detalle/index');
        }
        else
        {            
            $data['_view'] = 'detalle/add';
            $this->load->view('layouts/admin',$data);
        }
    }  

    /*
     * Editing a detalle
     */
    function edit($id)
    {   
        // check if the detalle exists before trying to edit it
        $data['detalle'] = $this->Detalle_model->get_detalle($id);
        
        if(isset($data['detalle']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_venta' => $this->input->post('id_venta'),
					'producto' => $this->input->post('producto'),
					'cantidad' => $this->input->post('cantidad'),
					'precio' => $this->input->post('precio'),
					'importe' => $this->input->post('importe'),
					'costo' => $this->input->post('costo'),
                );

                $this->Detalle_model->update_detalle($id,$params);            
                redirect('detalle/index');
            }
            else
            {
                $data['_view'] = 'detalle/edit';
                $this->load->view('layouts/admin',$data);
            }
        }
        else
            show_error('The detalle you are trying to edit does not exist.');
    } 

    /*
     * Deleting detalle
     */
    function remove($id)
    {
        $detalle = $this->Detalle_model->get_detalle($id);

        // check if the detalle exists before trying to delete it
        if(isset($detalle['id']))
        {
            $this->Detalle_model->delete_detalle($id);
            redirect('detalle/index');
        }
        else
            show_error('The detalle you are trying to delete does not exist.');
    }
    
}
