<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pago extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->require_min_level(1);
        if( !$this->is_role('admin') ){
            redirect('restringido');
        }
        $this->load->model('Pago_model');
    } 

    /*
     * Listing of pagos
     */
    function index()
    {
        $data['pagos'] = $this->Pago_model->get_all_pagos();
        
        $data['_view'] = 'pago/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pago
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_venta' => $this->input->post('id_venta'),
				'id_metodo' => $this->input->post('id_metodo'),
				'importe' => $this->input->post('importe'),
				'fecha' => $this->input->post('fecha'),
            );
            
            $pago_id = $this->Pago_model->add_pago($params);
            redirect('pago/index');
        }
        else
        {            
            $data['_view'] = 'pago/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pago
     */
    function edit($id)
    {   
        // check if the pago exists before trying to edit it
        $data['pago'] = $this->Pago_model->get_pago($id);
        
        if(isset($data['pago']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_venta' => $this->input->post('id_venta'),
					'id_metodo' => $this->input->post('id_metodo'),
					'importe' => $this->input->post('importe'),
					'fecha' => $this->input->post('fecha'),
                );

                $this->Pago_model->update_pago($id,$params);            
                redirect('pago/index');
            }
            else
            {
                $data['_view'] = 'pago/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pago you are trying to edit does not exist.');
    } 

    /*
     * Deleting pago
     */
    function remove($id)
    {
        $pago = $this->Pago_model->get_pago($id);

        // check if the pago exists before trying to delete it
        if(isset($pago['id']))
        {
            $this->Pago_model->delete_pago($id);
            redirect('pago/index');
        }
        else
            show_error('The pago you are trying to delete does not exist.');
    }
    
}
