<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Venta extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->require_min_level(1);
        if( !$this->is_role('admin') ){
            redirect('restringido');
        }
        $this->load->model('Venta_model');
    } 

    /*
     * Listing of ventas
     */
    function index()
    {
        $data['ventas'] = $this->Venta_model->get_all_ventas();
        
        $data['_view'] = 'venta/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new venta
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'pagada' => $this->input->post('pagada'),
				'cerrada' => $this->input->post('cerrada'),
				'id_cliente' => $this->input->post('id_cliente'),
				'id_usuario' => $this->input->post('id_usuario'),
				'id_mesa' => $this->input->post('id_mesa'),
				'fecha' => $this->input->post('fecha'),
            );
            
            $venta_id = $this->Venta_model->add_venta($params);
            redirect('venta/index');
        }
        else
        {            
            $data['_view'] = 'venta/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a venta
     */
    function edit($id)
    {   
        // check if the venta exists before trying to edit it
        $data['venta'] = $this->Venta_model->get_venta($id);
        
        if(isset($data['venta']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'pagada' => $this->input->post('pagada'),
					'cerrada' => $this->input->post('cerrada'),
					'id_cliente' => $this->input->post('id_cliente'),
					'id_usuario' => $this->input->post('id_usuario'),
					'id_mesa' => $this->input->post('id_mesa'),
					'fecha' => $this->input->post('fecha'),
                );

                $this->Venta_model->update_venta($id,$params);            
                redirect('venta/index');
            }
            else
            {
                $data['_view'] = 'venta/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The venta you are trying to edit does not exist.');
    } 

    /*
     * Deleting venta
     */
    function remove($id)
    {
        $venta = $this->Venta_model->get_venta($id);

        // check if the venta exists before trying to delete it
        if(isset($venta['id']))
        {
            $this->Venta_model->delete_venta($id);
            redirect('venta/index');
        }
        else
            show_error('The venta you are trying to delete does not exist.');
    }
    
}
